
export const SERVER_URL = "http://cafengockhanh.me";
export const API_ENDPOINT = SERVER_URL+"/server/index.php";
// export const BASE_IP_ADDRESS = "171.229.62.167";

export const SHOW_MODAL = "SHOW_MODAL";
export const CHANGE_MODAL_CONTENT = "CHANGE_MODAL_CONTENT";
export const CHANGE_MODAL_TITLE = "CHANGE_MODAL_TITLE"; 

export const SHOW_ADMIN_SIDEBAR = "SHOW_ADMIN_SIDEBAR"; 

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const REMOVE_PRODUCT_INFO = "REMOVE_PRODUCT_INFO";

export const FETCH_LIST_CATEROGY = "FETCH_LIST_CATEROGY";
export const FETCH_LIST_CATEROGY_SUCCESS = "FETCH_LIST_CATEROGY_SUCCESS";
export const FETCH_LIST_CATEROGY_FAILED = "FETCH_LIST_CATEROGY_FAILED";

export const REMOVE_CATEGORY_INFO = "REMOVE_CATEGORY_INFO";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const FETCH_CATEGORY_INFO = "FETCH_CATEGORY_INFO";
export const FETCH_CATEGORY_INFO_SUCCESS = "FETCH_CATEGORY_INFO_SUCCESS";
export const FETCH_CATEGORY_INFO_FAILED = "FETCH_CATEGORY_INFO_FAILED";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO";
export const GET_PRODUCT_INFO_SUCCESS = "GET_PRODUCT_INFO_SUCCESS";
export const GET_PRODUCT_INFO_FAILED = "GET_PRODUCT_INFO_FAILED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const FETCH_LIST_ARTICLE = "FETCH_LIST_ARTICLE";
export const FETCH_LIST_ARTICLE_SUCCESS = "FETCH_LIST_ARTICLE_SUCCESS";
export const FETCH_LIST_ARTICLE_FAILED = "FETCH_LIST_ARTICLE_FAILED";

export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILED = "ADD_ARTICLE_FAILED";

export const GET_ARTICLE_INFO = "GET_ARTICLE_INFO";
export const GET_ARTICLE_INFO_SUCCESS = "GET_ARTICLE_INFO_SUCCESS";
export const GET_ARTICLE_INFO_FAILED = "GET_ARTICLE_INFO_FAILED";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILED = "UPDATE_ARTICLE_FAILED";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILED = "DELETE_ARTICLE_FAILED";

export const GET_LIST_IMAGE = "GET_LIST_IMAGE";
export const GET_LIST_IMAGE_SUCCESS = "GET_LIST_IMAGE_SUCCESS";

export const ADD_IMAGE = "ADD_IMAGE";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";

export const DELETE_IMAGE = "DELETE_IMAGE";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";

export const CHECK_LOGIN = "CHECK_LOGIN";
export const CHECK_LOGIN_SUCCESS = "CHECK_LOGIN_SUCCESS";
export const CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";

export const GET_USER_INFO = "GET_USER_INFO";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";

export const LOGOUT = "LOGOUT";

export const ADD_KARAOKE_VIDEO = "ADD_KARAOKE_VIDEO";
export const GET_LIST_KARAOKE_VIDEO = "GET_LIST_KARAOKE_VIDEO";
export const DELETE_KARAOKE_VIDEO = "DELETE_KARAOKE_VIDEO";

export const GET_SITE_CONFIG = "GET_SITE_CONFIG";
export const CHANGE_SITE_CONFIG = "CHANGE_SITE_CONFIG";

export const SET_FULL_SCREEN = "SET_FULL_SCREEN";

export const GET_LIST_LAYOUT = "GET_LIST_LAYOUT";

export const GET_API_KEY = "GET_API_KEY";
export const CHANGE_API_KEY = "CHANGE_API_KEY";